
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.sound.sampled.LineUnavailableException;
import javax.sound.sampled.UnsupportedAudioFileException;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author NetImpact
 */
public class Piano extends javax.swing.JFrame {

    /**
     * Creates new form Piano
     */
    public Piano() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        b3 = new javax.swing.JButton();
        b18 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jButton28 = new javax.swing.JButton();
        b17 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("bajao");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, -1, -1));

        b3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b3.setText("e");
        b3.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 230, 50, 210));

        b18.setBackground(new java.awt.Color(0, 0, 0));
        b18.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b18.setForeground(new java.awt.Color(255, 255, 255));
        b18.setText("d#1");
        b18.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b18ActionPerformed(evt);
            }
        });
        getContentPane().add(b18, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, 70, 140));

        b4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b4.setText("f");
        b4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 50, 210));

        b5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b5.setText("g");
        b5.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 50, 210));

        b6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b6.setText("a");
        b6.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        getContentPane().add(b6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 50, 210));

        b7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b7.setText("b");
        b7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        getContentPane().add(b7, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 50, 210));

        b8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b8.setText("c1");
        b8.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        getContentPane().add(b8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 50, 210));

        b9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b9.setText("d1");
        b9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        getContentPane().add(b9, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 230, 60, 210));

        b10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b10.setText("e1");
        b10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        getContentPane().add(b10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 230, 50, 210));

        b11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b11.setText("f1");
        b11.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        getContentPane().add(b11, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 50, 210));

        b2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b2.setText("d");
        b2.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 50, 210));

        b16.setBackground(new java.awt.Color(0, 0, 0));
        b16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b16.setForeground(new java.awt.Color(255, 255, 255));
        b16.setText("bd");
        b16.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });
        getContentPane().add(b16, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 60, 140));

        b1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b1.setText("c");
        b1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 50, 210));

        jButton28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton28.setText("c1");
        jButton28.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton28ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 50, 210));

        b17.setBackground(new java.awt.Color(0, 0, 0));
        b17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b17.setForeground(new java.awt.Color(255, 255, 255));
        b17.setText("c#1");
        b17.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b17ActionPerformed(evt);
            }
        });
        getContentPane().add(b17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 60, 140));

        b12.setBackground(new java.awt.Color(0, 0, 0));
        b12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b12.setForeground(new java.awt.Color(255, 255, 255));
        b12.setText("c#");
        b12.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        getContentPane().add(b12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 50, 140));

        b15.setBackground(new java.awt.Color(0, 0, 0));
        b15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b15.setForeground(new java.awt.Color(255, 255, 255));
        b15.setText("g#");
        b15.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });
        getContentPane().add(b15, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 60, 140));

        b14.setBackground(new java.awt.Color(0, 0, 0));
        b14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b14.setForeground(new java.awt.Color(255, 255, 255));
        b14.setText("f#");
        b14.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });
        getContentPane().add(b14, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 60, 140));

        b13.setBackground(new java.awt.Color(0, 0, 0));
        b13.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b13.setForeground(new java.awt.Color(255, 255, 255));
        b13.setText("d#");
        b13.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });
        getContentPane().add(b13, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, 60, 140));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
       String path="C:\\Users\\NetImpact\\Desktop\\pinao\\piano\\E.wav";
        try {
            AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
            Clip player=AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (Exception e) {//yhn bhtcode tha delete kiya , bus try  catck mai band karna tha isko 
            
        
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b18ActionPerformed
       String path="C:\\Users\\NetImpact\\Desktop\\pinao\\piano\\D_s1.wav";
        try {
            AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
            Clip player=AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (Exception e) {//yhn bhtcode tha delete kiya , bus try  catck mai band karna tha isko 
            
        
        }
    }//GEN-LAST:event_b18ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
       String path="C:\\Users\\NetImpact\\Desktop\\pinao\\piano\\F.wav";
        try {
            AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
            Clip player=AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (Exception e) {//yhn bhtcode tha delete kiya , bus try  catck mai band karna tha isko 
            
        
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
       String path="C:\\Users\\NetImpact\\Desktop\\pinao\\piano\\G.wav";
        try {
            AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
            Clip player=AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (Exception e) {//yhn bhtcode tha delete kiya , bus try  catck mai band karna tha isko 
            
        
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
       String path="C:\\Users\\NetImpact\\Desktop\\pinao\\piano\\A.wav";
        try {
            AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
            Clip player=AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (Exception e) {//yhn bhtcode tha delete kiya , bus try  catck mai band karna tha isko 
            
        
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
       String path="C:\\Users\\NetImpact\\Desktop\\pinao\\piano\\B.wav";
        try {
            AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
            Clip player=AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (Exception e) {//yhn bhtcode tha delete kiya , bus try  catck mai band karna tha isko 
            
        
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
      String path="C:\\Users\\NetImpact\\Desktop\\pinao\\piano\\C1.wav";
        try {
            AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
            Clip player=AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (Exception e) {//yhn bhtcode tha delete kiya , bus try  catck mai band karna tha isko 
            
        
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
       String path="C:\\Users\\NetImpact\\Desktop\\pinao\\piano\\D1.wav";
        try {
            AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
            Clip player=AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (Exception e) {//yhn bhtcode tha delete kiya , bus try  catck mai band karna tha isko 
            
        
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
      String path="C:\\Users\\NetImpact\\Desktop\\pinao\\piano\\E1.wav";
        try {
            AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
            Clip player=AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (Exception e) {//yhn bhtcode tha delete kiya , bus try  catck mai band karna tha isko 
            
        
        }
    }//GEN-LAST:event_b10ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
       String path="C:\\Users\\NetImpact\\Desktop\\pinao\\piano\\F1.wav";
        try {
            AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
            Clip player=AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (Exception e) {//yhn bhtcode tha delete kiya , bus try  catck mai band karna tha isko 
            
        
        }
    }//GEN-LAST:event_b11ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
       String path="C:\\Users\\NetImpact\\Desktop\\pinao\\piano\\D.wav";
        try {
            AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
            Clip player=AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (Exception e) {//yhn bhtcode tha delete kiya , bus try  catck mai band karna tha isko 
            
        
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
     String path="C:\\Users\\NetImpact\\Desktop\\pinao\\piano\\Bb.wav";
        try {
            AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
            Clip player=AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (Exception e) {//yhn bhtcode tha delete kiya , bus try  catck mai band karna tha isko 
            
        
        }
    }//GEN-LAST:event_b16ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
       String path="C:\\Users\\NetImpact\\Desktop\\pinao\\piano\\C.wav";
        try {
            AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
            Clip player=AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (Exception e) {//yhn bhtcode tha delete kiya , bus try  catck mai band karna tha isko 
            
        
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void jButton28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton28ActionPerformed

    private void b17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b17ActionPerformed
     String path="C:\\Users\\NetImpact\\Desktop\\pinao\\piano\\C_s1.wav";
        try {
            AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
            Clip player=AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (Exception e) {//yhn bhtcode tha delete kiya , bus try  catck mai band karna tha isko 
            
        
        }
    }//GEN-LAST:event_b17ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
       String path="C:\\Users\\NetImpact\\Desktop\\pinao\\piano\\C_s.wav";
        try {
            AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
            Clip player=AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (Exception e) {//yhn bhtcode tha delete kiya , bus try  catck mai band karna tha isko 
            
        
        }
    }//GEN-LAST:event_b12ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
      String path="C:\\Users\\NetImpact\\Desktop\\pinao\\piano\\G_s.wav";
        try {
            AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
            Clip player=AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (Exception e) {//yhn bhtcode tha delete kiya , bus try  catck mai band karna tha isko 
            
        
        }
    }//GEN-LAST:event_b15ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
      String path="C:\\Users\\NetImpact\\Desktop\\pinao\\piano\\F_s.wav";
        try {
            AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
            Clip player=AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (Exception e) {//yhn bhtcode tha delete kiya , bus try  catck mai band karna tha isko 
            
        
        }
    }//GEN-LAST:event_b14ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
     String path="C:\\Users\\NetImpact\\Desktop\\pinao\\piano\\D_s.wav";
        try {
            AudioInputStream audio=AudioSystem.getAudioInputStream(new File(path));
            Clip player=AudioSystem.getClip();
            player.open(audio);
            player.start();
        } catch (Exception e) {//yhn bhtcode tha delete kiya , bus try  catck mai band karna tha isko 
            
        
        }
    }//GEN-LAST:event_b13ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Piano.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Piano().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b17;
    private javax.swing.JButton b18;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JButton jButton28;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
